; #Requires AutoHotkey v2.0
; #Include BuddyToolKit.ahk
#SingleInstance Force

; This is mostly just a bunch of text so I am not going to comment the whole lot of it. 
; 
; The basic gist is that each department tab has an array for the first dropdown and and array of arrays for the second dropdown.
; Each item in the first dropdowns arrays has an associated map containing key-value pairs. The keys in these pairs correlate with the items in the associated template array.
;
; The main script uses the two selected dropdown options to pull the value from the key-value pair and output it to a text field.

global CustomerName := IniRead("config.ini", "Customer", "CustomerName")
global CustomerNameSanitised := RegExReplace(CustomerName, "[^\w\s]")

csFullName := A_UserName
csFirstName := ""

if (RegExMatch(csFullName, "^[^.]*",&csFirstName)) {
csTitle:=StrTitle(csFirstName[0])
}

CurrentDate := FormatTime(, "yyyyMMdd")
NewDate := FormatTime(DateAdd(CurrentDate, 7, "days"), "dd/MM/yyyy")

GeneralReasons := ["LiveChat","OTRS", "Redmine/Jira"]
GeneralTemplates := [["Direct Link"],["Charges", "Closure", "Debit Validation Failed"],["Redmine Bug", "Redmine Enhancement"]]

AccountReasons := ["Payment Plan", "Financial Hardship"]
AccountTemplates := [["Set Up","Confirmation", "Payment Options", "Update Details"],["Template"]]

FaultReasons := ["General Templates","NBN","General Hardware","Discovery","Slow Speeds", "Dropouts", "No Connection", "Service Setup", "CSP Linking", "Hardware"]
FaultTemplates := [["Titles", "Warning", "Closing", "Checking in", "SRA/SOS/ROC"],["Raise", "Booked Appt"],["Resets", "Router Swap"],["General Issue", "Slow Speeds", "Dropouts", "No Connection"],["Direct Connection", "Wifi Limitations", "Bandsteering", "Line Rates"],["Bandsteering", "Stability Profile", "SRA", "Cabling"],["UNI-D Port", "Outage"],["VDSL", "EWAN"],["NBN", "Tracking"],["Local Issue", "Cabling"]]

DeliveryReasons := ["HFC", "FTTP", "FTTC", "Validation", "Banlisting", "Payment Failed", "Missing Payment Info", "Service Request", "Delays"]
DeliveryTemplates := [["Day 1","Day 2", "Day 3", "Multiple NTDs","Signal Issue"],["Multiple UNI-D"],["Day 1","Day 2", "Day 3", "Connect Router"],["Day 1","Day 2", "Day 3"],["Day 1"],["Day 1", "Day 2"],["Day 1","Day 2", "Day 3"],["NTD/Address Mismatch", "FTTP - Rebuild", "FTTN/B - SC12 No CPI", "FTTN/B - SC13 No CPI", "FTTN/B - FNN/ULL Dispute", "FTTN/B - Rebuild", "FTTN/B - POTS Rejection", "HFC - Urgent Completion", "HFC - Remote Activation", "HFC - Multiple NTDs", "Order Escalation"], ["TC4", "In-Flight Order", "In-Flight Fibre Connect", "Duplicate"]]

ComplaintReasons := ["NBN Complaints", "Raising", "Clarification", "Resolutions", "State Changes", "TIO", "Contacts"]
ComplaintTemplates := [["Templates"],["Templates"],["Templates"],["Templates"],["Changing PRD"],["Templates"],["SMS", "Email", "5 Attempts"]]

TCSReasons := ["General","Billing", "Suspension/Termination", "Changes"]
TCSTemplates := [["Availability", "Maintenance", "Support", "EU Obligations", "Data", "Access", ],["Fees", "Payment Methods", "Disputes", "Debit Dishonours", "Further Actions","Other Fees"],["Service Use", "Poor Behaviour", "Payment Issues"],["TOS Changes"]]

;---------------- General -----------------

UpdateTemplates() {

    global TemplatesMaps := Map(
        "LiveChat", LiveChatMap,
        "NBN", GeneralNBNMap,
        "General Hardware", GeneralHardwareMap,
        "OTRS", GeneralOTRSMap,
        "Redmine/Jira", RedmineJiraMap,
        "Payment Plan", PPMap,
        "Financial Hardship", FHMap,
        "General Templates",FaultTemplatesMap,
        "Discovery", DiscoveryMap,
        "Slow Speeds", SpeedsMap,
        "Dropouts", DropoutsMap,
        "No Connection", ConnectionMap,
        "Service Setup", SetupMap,
        "CSP Linking", LinkMap,
        "Hardware", HardwareMap,
        "HFC", HFCMap,
        "FTTP", FTTPMap,
        "FTTC", FTTCMap,
        "Validation", ValidationMap,
        "Banlisting", BanlistingMap,
        "Payment Failed", FailedPaymentMap,
        "Missing Payment Info", PaymentMap,
        "Service Request", ServiceRequestMap,
        "Delays", DelaysMap,
        "NBN Complaints", NBNCompMap,
        "Raising", RaisingMap,
        "Clarification", ClarificationMap,
        "Resolutions", ResolutionsMap,
        "State Changes", ChangesMap,
        "TIO", TIOMap,
        "Contacts", ContactsMap,
        "General", TCSGeneralMap,
        "Billing", TCSBillingMap,
        "Suspension/Termination", TCSSuspensionMap,
        "Changes", TCSChangesMap
    )
    
    global CustomerName, csTitle

    Global LiveChatMap := Map(
        "Direct Link", "https://direct.lc.chat/8184711/56"
    ) 

    Global GeneralNBNMap := Map(
        "Raise", Format("Hey " CustomerNameSanitised ",`n`nWe will need to raise this fault to NBN. `n`nPlease select from the following list of appointments or speak to our LiveChat team as the list will may not include the earliest available appointments.`n`n(Insert appts here)`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey Team`n`nCustomer is experiencing a (Insert Fault Type). `nTesting that has been done:`n(Insert T/S and test relevant test results)`n`nPlease investigate`n`nRegards,`nBuddy Telco"),

        "Booked Appt", "Hey " CustomerNameSanitised ",`n`nWe currently have enough information to raise a ticket with NBN and have a technician attend the property to resolve this fault for you.`n`nI have tentatively booked the following appointment slot for you:`n`n[Insert appointment slot]`n`nIf this slot does not work for you, you are able to reschedule the appointment yourself in this fault. If you would like you can also come through LiveChat at https://direct.lc.chat/8184711/56 and one of the team will rebook it for you.`n`nPlease be aware that someone over the age of 18 will need to be present and available for the chosen appointment.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nBuddy Telco here{!} We have booked a tentative NBN appointment in regards to your fault. Please log into the Buddy Telco app to check or reschedule this appointment{!}"
    ) 

    Global GeneralHardwareMap := Map(
        "Resets", "FTTC: Hey " CustomerNameSanitised ",`n`nIf the link light on your NBN device is red, please perform a factory reset on the device. `n`nYou can do this by locating the small hole labelled reset, and holding a pin, paperclip or SIM ejector tool into this for 15 seconds.`n`nOnce this is done, please let us know if the light is now blue again. `n`nIf this does not resolve the issue, please test using another DSL (Phone) cable, from the NBN device to the telephone port on the wall.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nFTTP: Hey " CustomerNameSanitised ",`n`nIf the optical light on your NBN device is red, please perform a factory reset on the device.`n`nYou can do this by locating the small hole labelled reset, and holding a pin, paperclip or SIM ejector tool into this for 15 seconds.`n`nPlease check to ensure the fibre optic cable is not damaged in any way. This is the thin yellow or white cable with the green connector. Avoid touching this cable if possible as it is very fragile.`n`nIf the issue does not resolve after the reset, or the cable is damaged, let us know as we may need to raise this to NBN`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHFC: Hey " CustomerNameSanitised ",`n`nWe will need you to perform a hard reset on the NBN NTD.`n`n1. Please unscrew the coaxial cable (TV antenna) from the NBN device.`n`n2. In the back of your nbn box there should be a little reset hole, please try holding a paperclip or pin in your nbn box for 15 seconds to reset it.`n`n3. Now screw the coaxial cable back in.`n`nIf the device does not fully restore after a minute or two please let us know.`n`nRegards,`n" csTitle "`n",

        "Router Swap", "Hey " CustomerNameSanitised ",`n`nPlease see the below instructions for switching your router for another device:`n`n1. Kick your connection using the service tests in the Buddy Telco App`n2. Unplug your Modem/Router from the NBN device`n3. Using the same cable from the NBN device, plug in your new router.`n4. Test the connection once the service becomes active`n`nRegards,`n" csTitle "",
    )

    Global GeneralOTRSMap := Map(
        "Charges", "Hey " CustomerNameSanitised ",`n`nThanks for reaching out. While I understand that the service has not been used, we are charged by NBN regardless and as such we do charge for the availability and not the usage.",

        "Closure", "Unfortunately, we are unable to close services via email. However, you can process the closure of your service through our app or web portal.`n`nAlternatively, you can contact our live chat team, who can assist you with the closure. They are available Monday to Friday, 12 PM–8 PM (AEDT).",

        "Debit Validation Failed", "Hey " CustomerNameSanitised ",`n`nJust reaching out as we have received notification that your direct debit pre-validation failed. This occurs when the direct debit information provided does not match a valid account.`n`nPlease reach out to us via LiveChat at https://direct.lc.chat/8184711/56 between the hours of 12pm - 8pm AEDT and we can add valid payment information to your account."
    )

    Global RedmineJiraMap := Map(
        "Redmine Bug", "Title: [Area affected] | [RSP affinity] | [Issue Effect]`n`nTicket Body:`n`nHi Team,`n`nPlease see the attached examples of the bug:`n[Insert links of affected apps/accounts. Confirm with supervisor/other staff that this is a bug first before raising.]`n`n**Issue:**`n[Insert the issue here describing in details what the identified root cause is. If unable to determine the root cause, please raise first in unleashed to request assistance in finding the root cause before raising bug ticket]`n`n**Provider Impact:**`n[Impact is RSP specific, RSP agnostic or unknown. If this is application related, please raise issue to delivery support for investigating if the issue affects other RSP's too. If this is CS related, please raise with ABB staff to see if this occurs with Aussie variants of accounts.]`n`n**Date Issue First Noticed:**`n[Investigate first known occurrence of issue. This will assist systems owners and devs to find the possible merge that caused the bug]`n`n**Process deviation:**`n[List the process that normally occurs and at which point these examples deviate from that process]`n`n**Steps to reproduce:**`n[List each step from start to finish where the issue began. Insert screen shots of each affected area causing the bug.]`n`ne.g.`n1. Customer submits application via webpage with incorrect install type`n[Insert screen shot identifying the affected part of the app]`n2. Customer validates app`n3. App passes pre-checks`n4. Order submits to NBN`n5. Order rejects due to invalid CPI`n6. Order falls to manual queue",

        "Redmine Enhancement", "Title : [Area of improvement] | [Change suggestion]`n`nTicket Body:`n`nHey Team,`n`nI would like to suggest the following change to [Insert System/Process]`n`n**Current process:**`n[Outline the current process and how it is completed including all steps]`n`n**Existing blockers/hurdles:**`n[Explain your issues with the current system and what causes it to take longer/be harder than it could be. Be unbiased and professional, these systems were written by a human]`n`n**Change information:**`n[Write out the change that you think should be implemented. Be as detailed as required to accurately explain the change you would like to see]`n`n**Business benefits:**`n[Why is this change worth it? Consider the dev time, wage cost and any potential downsides to the change. What value does this change add to the company and how does it improve the workflow of the staff who interact with the system]`n`n**Related Pages:**`n[Does this affect more than just the system being changed? If so link the pages or systems that would be affected]"
    )

    ; --------------- Accounts ----------------

    Global PPMap := Map(
        "Set Up", "Hey " CustomerNameSanitised ",`n`nIf you would like to set up a payment plan, you can do so in the billing section of the Buddy Telco App.`n`nNavigate to the Billing tab at the bottom of the app`nTap the Request a Payment Extension button`nEnter your preferred payment date`n`nYou will receive email confirmation once the plan has been set.`n`nRegards,`n" csTitle "",

        "Confirmation", "Hey " CustomerNameSanitised ",`n`nWe have set the payment plan that you have requested. You should receive a confirmation email outlining the details shortly.`n`nRegards,`n" csTitle "",

        "Payment Options", "Hey " CustomerNameSanitised ",`n`nThe payment methods we currently accept are direct debit and card payments. If you would like to update your payment details you can do this through the billing section of the app.`n`nRegards,`n" csTitle "",

        "Update Details", "Hey " CustomerNameSanitised ",`n`nIf you would like to update your payment details, you can do so through the billing section of the Buddy Telco App.`n`nNavigate to the Billing tab at the bottom of the app`nTap the edit button next to payment method at the top`nComplete the 2FA via SMS or Email`nEnter your new billing information`n`nYour payment details are now updated.`n`nRegards,`n" csTitle "",
    )

    Global FHMap := Map(
        "Template", "Hi [Customer],`n`nThank you for submitting your application for financial hardship payment assistance. To progress your application, we will require you to provide some supporting information to assess your eligibility.`n`nThis can be in the form of:`nIncome statement`nExpense statement`nDocumentation from a financial counsellor`nOther documentation showing circumstances related to financial hardship`n`nYou can respond to this email with your documents or send them to hardship@buddytelco.com.au`n`nWe will consider any documents relating to income, statements from advisors and your past payment history with us when we make an assessment.`n`nWe only request this information when it is necessary for us to assess eligibility. We will only retain a copy or record of any information you provide us, for as long is required to complete our assessment of your application. We may not be able to assess your circumstances if you don't provide us with the requested information. However, we also understand that sometimes (for example, if you are experiencing domestic or family violence) you may not be able to provide documents.`n`nWe're here to help. Give us a call to discuss your application with one of our Financial Hardship Officers by phone on 1300 028 339 (12pm to 8pm AEDT).",
    )

    ;------------------- Faults -----------------------

    Global FaultTemplatesMap := Map(
        "Titles", "No Connection`n`nService Setup`n`nService Never Worked`n`nSpeeds`n`nDropouts`n`n",

        "Warning", "Hey " CustomerNameSanitised ",`n`nJust wanted to reach out to see if you still needed a hand with this fault?`n`nIf we don`'t hear back from you within the next day or so we will close the fault off, but we can re-open it in the future if we need to.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey, Buddy Telco here. Just a quick reminder to jump on the app and check the response to your fault.`n`n------------------------------`n`nHey, Buddy Telco here. Just a quick reminder to check our email response to your ticket.",

        "Closing", Format("Hey " CustomerNameSanitised ",`n`nSince we didn't hear back we will close this fault off but if you need us to investigate in future just let us know.`n`nRegards,`n" csTitle "" ),

        "Checking in", "Hey " CustomerNameSanitised ",`n`nJust reaching out to let you know that we still have this fault open and are actively monitoring it. We are just waiting for an update from NBN to provide to you.`n`nIf you have any questions or requests of us here in the mean time feel free to reach out{!}`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nI wanted to let you know that we are still actively checking in on your fault. NBN have placed it in a monitoring period for 7 days. If it fails this period we will reach out to book another appointment for you.`n`nIf you have any questions or requests of us here in the mean time feel free to reach out{!}`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nI wanted to let you know that we are still actively checking in on your fault. NBN have placed the ticket in a held state while they investigate some issue that are occurring further upstream. We will keep you in the loop with any updates that they provide to us.`n`nIf you have any questions or requests of us here in the mean time feel free to reach out{!}`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nNBN have let us know their technician has attended and it looks like the service is now passing our testing.`n`nBefore we close this fault off we would love to hear from you to confirm if everything is now working as expected. Please do let us know if you are still experiencing any issues with the service so we can continue investigating.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe'd love to continue to investigate this for you but haven't heard back from you in a while.`n`nPlease get back to us when you can either by reaching back out here in your app fault, or directly through LiveChat at https://direct.lc.chat/8184711/56`n`nRegards,`n" csTitle "",

        "SRA/SOS/ROC", "SRA and SOS/ROC are protocols that ensure the router remains connected at the correct frequency. When the router first syncs with the NBN line it syncs at the current line rate. SRA and SOS/ROC allow it to change to different line rates when the frequency on the incoming copper changes. If SRA and SOS/ROC are not showing on the NBN testing or are not available settings on the router this can cause dropouts and speed fluctuations. If the settings are not available in the router, it may need a firmware upgrade, or the router may not be compatible.{Enter 2}"
    )

    Global DiscoveryMap := Map(
        "General Issue", "Hi xxx,`n`nThanks for taking the time to reach out, we hope you're well. We understand how important a reliable connection is, and I'd like to help resolve this as quickly as possible.`n`nCould you please let me know:`nAre you experiencing this issue on all your devices or just specific ones?`nAre your devices connected via Wi-Fi or an Ethernet cable?`n`nKnowing this will help me identify whether it's a network issue or something related to a particular device or connection method. In the meantime, have you tried restarting your modem/router? Unplugging it for about 30 seconds and plugging it back in can often resolve connectivity issues.`n`nPlease let me know, and I'll do my best to assist you further.`n`nBest regards,`n" csTitle "",

        "Slow Speeds", "Hi xxx,`n`nThank you for reaching out about the slow internet speeds you've been experiencing. I know how frustrating that can be, and I'm here to help.`n`nCould you let me know the following:`nIs the slow speed happening all the time or only at certain times of the day?`nAre specific activities affected, like streaming videos or browsing websites?`nAre your devices connected via Wi-Fi or an Ethernet cable?`n`nThis information will help me understand the nature of the issue and provide the best solution. While we look into this, it might help to restart your modem/router by unplugging it for 30 seconds and plugging it back in.`n`nLet me know, and we'll work together to improve your internet speed.`n`nBest regards,`n" csTitle "",

        "Dropouts", "Hi xxx,`n`nI'm sorry to hear that your internet connection has been dropping out. I understand how disruptive that can be, and I'm here to assist.`n`nCould you please let me know:`nHow often does the dropout occur?`nDoes it happen during specific activities or times of the day?`nAre your devices connected via Wi-Fi or an Ethernet cable?`n`nThis will help me identify any patterns that might point to the cause of the issue. In the meantime, try restarting your modem/router if you haven't already, as this can sometimes resolve the problem.`n`nPlease get back to me when you can, and we'll find a solution together.`n`nBest regards,`n" csTitle "",

        "No Connection", "Hi xxx,`n`nSorry to hear that you're unable to connect to the internet. I understand how essential it is to stay connected, and I'm here to assist you in getting back online as soon as possible.`n`nCould you please let me know:`nAre all your devices unable to connect, or is it just one device?`nAre your devices connected via Wi-Fi or an Ethernet cable?`n`nThis information will help me determine whether the issue is affecting your entire network or a specific device or connection type. In the meantime, have you tried restarting your modem/router? Unplugging it from the power source for about 30 seconds and then plugging it back in can often resolve connectivity issues.`n`nPlease let me know when you have a moment, and I'll do everything I can to help restore your internet connection.`n`nBest regards,`n" csTitle ""
    )

    Global SpeedsMap := Map(
        "Direct Connection", "Hey " CustomerNameSanitised ",`n`nCan you please run some direct connection speed tests? This will show us whether the speeds coming directly from NBNco are poor or not, if the results show an issue it acts as evidence should we need to raise this to nbn.`n`nDirect connection speed test instructions:`n`n1. Kick your connection using the service tests in Buddy app`n2. Unplug your Modem/Router from the NBN device`n3. Using the same cable from the NBN device, plug in a laptop or computer.`n4. Run 3-5 speed tests through www.speedtest.net`n5. Reply to us with the Result IDs the tests generate `n6. Kick the connection again via the Buddy App`n7. Swap from the laptop/PC to the Modem/Router `n`nIf you have any further questions, issues or concerns, reply here or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nRegards,`n" csTitle "",

        "Wifi Limitations", "Hey " CustomerNameSanitised ",`n`nWiFi speeds are unfortunately not a good indicator of achievable service speeds.`n`nIt is possible to improve the speeds by adjusting the frequency and channels of the WiFi, which we can provide instructions for, however the automatic mode on most routers is sufficient. What is more likely to help is assessing environmental factors such as distance, line of sight and interference.`n`nTo limit interference please ensure that the router is connected to power on its own socket, not in a power board, and avoid placing it near large white good appliances or microwaves. Metal objects do block WiFi signals so avoid having large metal objects between your router and connected devices.`n`nRegards,`n" csTitle "",

        "Bandsteering", "Hey " CustomerNameSanitised ",`n`nMost modern routers have two WiFi bands, 2.4Ghz and 5Ghz. The 2.4 band has higher range but a lower total throughput, and the 5 band has lower range but higher throughput. If you only see one wifi channel from your router, it means that a setting called band steering is combining the band for you, and negotiating which devices connect to which channel.`n`nFor most scenarios this is ideal, however band steering can sometimes default your devices to the 2.4Ghz band, causing lower than expected speeds.`n`nIn these instances we can walk you through disabling the band steering option on your router if it is available.`n`nRegards,`n" csTitle "",

        "Line Rates", "Below Spec: Hey " CustomerNameSanitised ",`n`nYour service has fallen below NBN specifications, which means we know it is an infrastructure issue and we can raise a ticket to NBN.`n`nPlease select from one of the below available appointments.`n`n(Insert appts here)`n`nRegards,`n" csTitle "`n`n------------------------------`n`nAbove Spec: Hey " CustomerNameSanitised ", `n`nNBN does a minimum assured speed for each FTTN and FTTC service. At this stage your service is currently above that specification which means we need to do some more local troubleshooting.`n`n(Insert instructions or discovery questions here)`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHFC: Hey " CustomerNameSanitised ", `n`nThe speed specifications for HFC is approximately 50% of the plan speed. In the case of high speed services the minimum specifications are:`n1000/50 plan then the minimum speed is 501/25.`n250/25 plan then the minimum speed is 126/12.`n`nTo determine this we will need you to run direct connection tests from a laptop or PC directly to the NBN device.`n`nDirect connection speed test instructions:`n1. Kick your connection using the service tests in the Buddy Telco App`n2. Unplug your Modem/Router from the NBN device`n3. Using the same cable from the NBN device, plug in a laptop or computer.`n4. Run 3-5 speed tests through www.speedtest.net[/url]`n5. Reply to us with the Result IDs the tests generate `n6. Kick the connection again via the Buddy App`n7. Swap from the laptop/PC to the Modem/Router `n`nRegards,`n" csTitle "`n`n------------------------------`n`nFTTP: Hey " CustomerNameSanitised ",`n`nThe speed specifications for FTTP is approximately 50% of the plan speed. In the case of high speed services the minimum specifications are:`n1000/50 plan then the minimum speed is 501/25.`n250/25 plan then the minimum speed is 126/12.`n`nTo determine this we will need you to run direct connection tests from a laptop or PC directly to the NBN device, as NBN will not accept tests done over Wi-Fi or ethernet to the router.`n`nDirect connection speed test instructions:`n1. Kick your connection using the service tests in the Buddy Telco App`n2. Unplug your Modem/Router from the NBN device`n3. Using the same cable from the NBN device, plug in a laptop or computer.`n4. Run 3-5 speed tests through www.speedtest.net[/url]`n5. Reply to us with the Result IDs the tests generate `n6. Kick the connection again via the Buddy App`n7. Swap from the laptop/PC to the Modem/Router `n`nRegards,`n" csTitle ""
    )

    Global DropoutsMap := Map(
        "Bandsteering", "Hey " CustomerNameSanitised ",`n`nMost modern routers have two WiFi bands, 2.4Ghz and 5Ghz. The 2.4 band has higher range but a lower total throughput, and the 5 band has lower range but higher throughput. If you only see one wifi channel from your router, it means that a setting called band steering is combining the band for you, and negotiating which devices connect to which channel.`n`nFor most scenarios this is ideal, however band steering can sometimes cause your devices to disconnect when attempting to switch from one band to another. This will present as micro-dropouts, usually when roaming around the house.`nIn these instances we can walk you through logging into your router.`n`nRegards,`n" csTitle "",

        "Stability Profile", "Apply: Hey  xxx,`n`nIn order for us to raise this as a dropouts fault with NBN, we need to apply a stability profile and monitor the connection for 48 hours. The profile can negatively affect speeds to a degree. Please let us know when it would be an appropriate time for us to apply this, as it will cause the router to lose connection momentarily. `n`nRegards,`n" csTitle "`n`n------------------------------`n`nRemove: Hey " CustomerNameSanitised ",`n`nAs the testing now shows no dropouts we could now look at removing the stability profile on your service to return your speeds back to normal. When we do this, you will initially experience a dropout whilst your modem re-syncs. `n`nRegards,`n" csTitle "",

        "SRA", "Hey " CustomerNameSanitised ",`n`nSRA and SOS/ROC are protocols that ensure the router remains connected at the correct frequency. When the router first syncs wit DSL/RJ11 cable. (This is ah the NBN line it syncs at the current line rate. SRA and SOS/ROC allow it to change to different line rates when the frequency on the incoming copper changes. If SRA and SOS/ROC are not showing on the NBN testing or are not available settings on the router this can cause dropouts and speed fluctuations. If the settings are not available in the router, it may need a firmware upgrade, or the router may not be compatible.`n`nRegards,`n" csTitle "",

        "Cabling", "Hey " CustomerNameSanitised ",`n`nDue to the number of external factors that can affect WiFi signals, we are unable to isolate dropouts faults using WiFi troubleshooting.`nAre you able to connect a device such as a laptop or PC to the router using an ethernet cable and test to see if the dropouts still occur?`n`nAnother good way to tell the difference is if your mobile phone will switch back to mobile data when the dropout occurs. If it does, you likely have a local WiFi issue.`n`nRegards,`n" csTitle ""
    )

    Global ConnectionMap := Map(
        "UNI-D Port", "Hey " CustomerNameSanitised ",`n`nIt looks like your router might be plugged into the wrong port on the NBN device. `n`nEnsure that your router is connected to (Insert UNI-D port).`n`nRegards,`n" csTitle "",

        "Outage", "Ongoing: Hey " CustomerNameSanitised ",`n`nUnfortunately at this stage your service is being affected by an outage. We do not currently have an ETA on a fix but the issue is currently being investigated.`n`nIf you have any further questions, issues or concerns, feel free to simply reply back to this message or reach out to our support team via LiveChat from our website or within the Buddy Telco App.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nResolved: Hey " CustomerNameSanitised ",`n`nIt does appear that your service was being affected by an outage that has since been resolved, if you are still having issues please power-cycle your router (turn off and on).`n`nIf the issue has been resolved alongside that outage let us know and we`'ll close this fault off, otherwise we may close this fault as resolved anyway within 24 hours `n`nRegards,`n" csTitle ""
    )

    Global SetupMap := Map(
        "VDSL", "Hey " CustomerNameSanitised ",`n`nPlease find the below settings for your VDSL connection. Bear in mind that these are generic settings, and may vary in name based off your router brand. `nLog into your router using the IP address/URL on the bottom/back of the router. (It might look like 192.168.0.1)`nEnter the username and password located near that IP address/URL. Locate the Setup Connection section or enter the quick setup.`n`nConnection Mode: VDSL`nConnection Type: Dynamic IP `nPrimary: 202.142.142.142`nSecondary: 202.142.142.242`n802.11P: -1`nVLAN Tag: -1`nNAT: Enabled`nFirewall: Enabled`nMTU Size: 1500 `nMSS Size: 1460`nIP Protocol: IPv4/IPv6 `nDHCPv6 (IANA): Enabled`nDHCPv6 (IAPD): Enabled`nIGMP: Enabled`n`nRegards,`n" csTitle "",

        "EWAN", "Hey " CustomerNameSanitised ", `n`nPlease find the below settings for your EWAN connection. Bear in mind that these are generic settings, and may vary in name based off your router brand. `nLog into your router using the IP address/URL on the bottom/back of the router. (It might look like 192.168.0.1)`nEnter the username and password located near that IP address/URL. Locate the Setup Connection section or enter the quick setup.`n`nConnection Mode: EWAN or Ethernet WAN`nConnection Type: Dynamic IP `nPrimary: 202.142.142.142`nSecondary: 202.142.142.242`n802.11P: -1`nVLAN Tag: -1`nNAT: Enabled`nFirewall: Enabled`nMTU Size: 1500 `nMSS Size: 1460`nIP Protocol: IPv4/IPv6 `nDHCPv6 (IANA): Enabled`nDHCPv6 (IAPD): Enabled`nIGMP: Enabled`n`nRegards,`n" csTitle ""
    )

    Global LinkMap := Map(
        "NBN", "NBN Appointment ID:`n`nNBN Incident ID:",
        "Tracking", "Return Post Tracking Code:"
    )

    Global HardwareMap := Map(
        "Local Issue", "Hey " CustomerNameSanitised ",`n`nIt looks like the issue might be with your local hardware. We`'re happy to help you troubleshoot to ensure the NBN infrastructure isn`'t part of the problem. However, if the fault is due to your devices, we can`'t guarantee a fix. This also applies to WiFi issues, as we can`'t confirm the perfect conditions for wireless signals.`n`nRegards,`n" csTitle "",

        "Cabling", "FTTN/FTTB: Hey " CustomerNameSanitised ",`n`nTo connect your FTTN/FTTB service, please follow the cabling guide below:`n`n1. Ensure that the router is connected to power near your active phone port. (If you have more than one it is usually the closest to the front of the house)`n2. Connect the DSL port on your router to the phone port on the wall using a DSL/RJ11 cable. (This is a phone cable)`n3. Configure your router. `n`nIf you need assistance configuring your router please see the router guides on our site.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHFC: Hey " CustomerNameSanitised ",`n`nTo connect your HFC service, please follow the cabling guide below:`n`nEnsure that the NBN device is connected to power and the coaxial port on the wall. This looks like a TV antenna cable that screws on.`nConnect your router using an ethernet cable from the WAN port to the UNI-D port on the NBN device. Depending on the router model it may also say LAN1/WAN`nConfigure your router. `n`nIf you need assistance configuring your router please see the router guides on our site.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nFTTC: Hey " CustomerNameSanitised ",`n`nTo connect your FTTC service, please follow the cabling guide below:`n`n1. Ensure that the NBN device is connected to power near your active phone port. (If you have more than one it is usually the closest to the front of the house)`n2. Connect the NBN device from the wall socket port to the phone port on the wall using a DSL/RJ11 cable`n3. Connect your router to power near the NBN device.`n4. Connect your router from its WAN port to the Gateway port on the NBN device `n5. Configure your router. `n`nIf you need assistance configuring your router please see the router guides on our site.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nFTTP: Hey " CustomerNameSanitised ",`n`nTo connect your FTTP service, please follow the cabling guide below:`n`n1. Ensure that your NBN device is powered on.`n2. Connect your router to power near the NBN device and power it on.`n3. Connect your router from the WAN port to the UNID-1 port on the NBN device using an ethernet cable.`n4. Configure your router`n`nIf you need assistance configuring your router please see the router guides on our site.`n`nRegards,`n" csTitle ""
    )

    Global ServiceRequestMap := Map(
        "NTD/Address Mismatch", "Request Type:  Equipment`nSeverity:  NTD Issue`n`nHi Team,`n`nYour records show that [INSERT NTD SERIAL NUMBER] is installed at [INSERT LOCID]. We have confirmed with our EU that actually [INSERT NTD SERIAL NUMBER] is installed onsite.`n`n- [INSERT PRI] has been deleted`n- Proof of Occupancy and Photos of the NTD (including Mac and Serial details) have been emailed to: proofofaddress@nbnco.com.au referencing this incident ID.`n`nPlease amend your records to reflect the correct NTD installed at [INSERT LOCID] so we can proceed with a connection for our EU.`n`nThank you.",

        "FTTP - Rebuild", "Hi Team,`n`nWe have been informed by our EU that [INSERT LOCID] has been knocked down and rebuilt and the cable and PCD have been removed from site. Please arrange to have [INSERT LOCID] rolled back to [INSERT ANTICIPATED SQ].`n`nPlease see the following supporting information:`n- Was the PCD previously installed onsite? YES`n- Can the EU locate where the PCD was located? YES/NO`n- Is the cabling from the PCD to the NTD original location still present? YES/NO`n- Who was responsible for the removal of this equipment?`nName`nMobile`nEmail`n`nPlease note Proof of Occupancy and supporting photos have been emailed to proofofaddress@nbnco.com.au referencing this incident number.`n`nPlease proceed with rolling back [INSERT LOCID] to [INSERT ANTICIPATED SQ] so we can arrange a connection for our EU.`n`nThank you",

        "FTTN/B - SC12 No CPI", "Request Type:  FNN/ULL Dispute`nSeverity: Low`nFNN: 0399999999`n`nHi Team,`n`nLOC is currently SC12 with no CPIs listed.`n`nPlease amend your records to reflect the SC12 CPI at this address or if there are no records of CPIs at this address, please roll back LOC to SC11. `n`nPlease rectify this issue so we can proceed with an order for our EU.`n`nThank you.",

        "FTTN/B - SC13 No CPI", "Request Type:  FNN/ULL Dispute`nSeverity: Low`nFNN: 0399999999`n`nHi Team,`n`nPlease amend your records to reflect the active SC13 CPI at [INSERT LOCID].`n`n[INSERT LOCID] is SC13 with no active CPI's and we can confirm that there has been an active nbn service at this address.`n`nPlease rectify this so we can raise an order for our EU.`n`nThank you.",

        "FTTN/B - FNN/ULL Dispute", "Request Type:  FNN/ULL Dispute`nSeverity:  Low`n`nHi Team`n`nPlease align FNN/ULL [INSERT FNN/ULL] against [INSERT LOCID] we can confirm that this is a valid match against this address.`n`nPlease rectify this so we can raise an order for our EU.`n`nThank you ",

        "FTTN/B - Rebuild", "Request Type:  Address`n`nSeverity:  Incorrect Service Class Returned`n`nHi Team,`n`nWe have been informed by our EU that [INSERT LOCID] has been knocked down and rebuilt and cabling has been removed from site. Please arrange to have [INSERT LOCID] rolled back to [INSERT ANTICIPATED SQ].`n`nPlease see the following supporting information:`n`nWas the NBN previously installed onsite? YES/NO`nIs the conduit from the Property boundary to the premise present? YES/NO is the internal cabling in place ? ( first socket)`nWho knocked it down/removed the cables?`nName`nEmail`nMobile`n`nPlease note Proof of Occupancy and supporting photos have been emailed to proofofaddress@nbnco.com.au referencing this incident number.`n`nPlease proceed with rolling back [INSERT LOCID] to [INSERT ANTICIPATED SQ] so we can arrange a connection for our EU.`n`nThank you. ",

        "FTTN/B - POTS Rejection", "Request Type:  Order`nSeverity:  Order Error`n`nHi Team,`n`nWe raised [ORDER ID] and this was rejected due to the following reason:`n`nOrder status: Rejected`nReason code: RJ005177`nDescription: The supplied FNN or ULL ID provided for the POTS Interconnect was not found against the Copper Pair identified in the request`n`nWe are trying to place our order against the inactive CPI at [INSERT LOCID] therefore a FNN/ULL is not required. Please amend your records so we can proceed with an order for our EU.`n`nThank you.",

        "HFC - Urgent Completion", "Request Type:  Equipment`nIssue:  Remote Activation Request`n`nHi Team,`n`nWe require [INSERT ORDER ID] to be completed urgently.`n`nThe EU has DHCP logs and recent usage against:`nLocation ID:`nAVC:`nC-TAG:`nProduct Instance ID:`n`nArris NTD details are as follows:`n[MAC ADDRESS]`n[SERIAL NUMBER]`nArris NTD light status: ON/OFF`n* 4 green light on - Y / N`n* Upstream light is flashing orange - Y / N`n* Downstream light is flashing orange - Y / N`n* lights are cycling between Upstream / Downstream / Online - Y/N`n`nEU is currently receiving a free service. Please complete this order ASAP.`n`nThank you.",

        "HFC - Remote Activation", "Request Type:  Equipment`nSeverity:  Remote Activation Request`n`nHi Team,`n`nPlease proceed with remote activation for [INSERT ORDER ID].`n`nWe can confirm that there is an Arris NTD installed onsite and is powered on. Arris NTD details are as follows:`n[MAC ADDRESS]`n[SERIAL NUMBER]`nArris NTD light status: ON/OFF`n* 4 green light on - Y / N`n* Upstream light is flashing orange - Y / N`n* Downstream light is flashing orange - Y / N`n* lights are cycling between Upstream / Downstream / Online - Y/N`n`nOur customers details are:`n" csTitle "`n" csTitle "x`nXx`n`nPlease remotely activate this service so we can get out EU online.`n`nThank you. ",

        "HFC - Multiple NTDs", "Request Type:  Equipment`nSeverity:  NTD Issue`n`nHi Team,`n`nYour records show that there is multiple Arris NTDs installed onsite at [INSERT LOCID].`n`nIn order for us to place our order against the correct NTD, can you please advise what NTD ID the following Mac & Serial details belong to?`n`n[MAC ADDRESS]`n[SERIAL ADDRESS]`n`nPlease advise so we can proceed with an order for our EU.`n`nThank you",

        "Order Escalation", "Email Subject:`n`nSR INC: [INC ID] | [AUSSIE REF] | Activations | [TECHONOLOGY TYPE i.e. HFC/FTTB]`n`nEmail Body:`n`nOrder Number:  If there is no order ID, please put N/A order`nLOC ID:  [INSERT LOC ID]`nAppointment ID:  If there is no apt ID, please put N/A`nTIO Raised:  If no TIO has been raised please put NOre `nTIO Ref:  If no TIO raised, please put N/A`n`nIssue:`n[Explain what the issue is, generally what is written in the INC]`n`nReason for escalation:`n[Explain why you’re escalating this to the escalations team. Ie. Issue was not resolved/no response within required time frame etc] "
    )

    Global DelaysMap := Map(
        "TC4", "Hi " CustomerNameSanitised ",`n`nJust reaching out as your order has been delayed. We have received an error from NBN that you are on a higher tier plan with your previous provider. As a result, this would necessitate us closing off that service to open a gigabit plan.`n`nThe main issue is this would likely result in the application needing manual intervention in the morning and as we are not in the office until Monday, will result in significant downtime.`n`nTo alleviate this and get the connection active immediately, there are two options:`n`n1. Please request your current provider immediately downgrade your plan speeds to 100/40 or lower. Once this has been completed, pop into the LiveChat and we can connect your service with us on another port top ensure as little downtime as possible. If choosing this option, please confirm with your provider they have definitely downgraded the plan immediately as we will not be able to order until that has completed.`n`n2. Lower your connected plan with us to get the connection online on another port, close off your old service with your previous provider and then upgrade your plan the day following the closure. This will ensure that your service goes live and that you have minimal downtime also.`n`nEither way, just pop into the LiveChat and we can assist, we are open Mon-Fri 12-8pm AEDT.`n`nIf we haven't heard from you by close of business today, this service won't transfer until Monday evening.",

        "In-Flight Order", "NBN Order Held`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nThanks for ordering your NBN with us{!}`n`nWe have had a small hiccup. NBN is telling us there is already an order pending for your premises.`n`nIf you have recently spoken to another retail service provider about an NBN connection, this will probably be what is holding up the process.`n`nIf you wish to go ahead with your broadband order, please:`n`n1. Cancel any orders you may have with other providers.`n2. Let us know by contacting us or responding to this email.`n`nOnce we hear from you, we will re-submit your order immediately!`n`nDue to strict privacy guidelines, we cannot remove pending orders with NBN if they are in place with another service provider, this can only be done with the customer and the service provider in question.`n`nYour order will remain on hold until this order with the other provider has been removed.`n`n------------------------------`n`nHey, Buddy Telco here{!} We are unable to progress your order as there appears to be an order with another ISP in progress. Please reach out to our LiveChat team when possible.",

        "In-Flight Fibre Connect", "Thanks for ordering your NBN with us{!}`n`nWe have had a small hiccup. NBN is telling us there is already an order pending for your premises.`n`nIf you have recently spoken to another retail service provider about an NBN Fibre connection, this will probably be what is holding up the process.`n`nIf you wish to go ahead with your broadband order, please get in contact via LiveChat to advise when the current provider is due to complete your fibre install.`n`nOnce we hear from you, we will need to 2fa to move the connection date back to when that install is complete.`n`nYour order will remain on hold until this order with the other provider has been completed.",

        "Duplicate", "Duplicate Order`n`n------------------------------`n`nHey " CustomerNameSanitised "`n`nIt looks like you have a duplicate order with us. This can occur for a number of reasons, but we want to make sure you do not need two NBN services at your address. `n`nPlease reach out to our support team via LiveChat between the hours of 12pm - 8pm AEDT by visiting this link: https://direct.lc.chat/8184711/56`n`nThe team will help you abandon the duplicate order if you do not require it. If we do not hear from back from you by " newDate " the duplicate order will be automatically abandoned`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey, Buddy Telco here{!} It looks like you have a duplicate order with us. Please reach out to our LiveChat team if you would like to abandon that order."

    )

    Global HFCMap := Map(
        "Day 1", "HFC Activation`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to update you on your recent NBN order. It`'s currently delayed because NBNs system can`'t detect the NTD connected. Ensure the coaxial cable is securely connected to the back of the NBN NTD and that the device is powered on.`n`nAdditionally, they have asked us to verify the MAC address and serial number of your HFC NTD. This information can be found on the sticker at the bottom of the device. Please reply to this email with that information or a photo of the sticker, and we`'ll take it from there.`n`nIf you have any questions, you can reach out here or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nThanks for your understanding. We can`'t wait to get you up and running.`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team so we can get things moving. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nSMS and Email Sent",

        "Day 2", "HFC Abandonment`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to update you on your recent NBN order. It`'s currently delayed because NBNs system can`'t detect the NBN NTD connected. Ensure the coaxial cable is securely connected to the back of the NBN NTD and that the device is powered on.`n`nAdditionally, NBN has asked us to verify the MAC address and serial number of your HFC NTD. This information can be found on the sticker at the bottom of the device. Please reply to this email with that information or a photo of the sticker, and we`'ll take it from there.`n`nIf you have any questions, you can reach out here or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nIf we don`'t hear from you by " newDate ", we`'ll have to abandon your order. We don`'t want you to miss out, so please reach out soon.`n`nThanks for your understanding. We can`'t wait to get you up and running.`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team before " newDate " or we will have to abandon your order. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nAbandonment date set " newDate " ",

        "Day 3", "Order Abandoned`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing well.`n`nSince we haven`'t heard back from you, we`'ve Abandoned your NBN order. But don`'t worry, it`'s super easy to sign back up on our website.`n`nNeed help signing up? Just hop onto our live chat, and our friendly team will be happy to assist you. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nHave a great day.`n`n------------------------------`n`nHey there. It`'s Buddy Telco. Since we haven`'t heard from you, we`'ve abandoned your NBN order. You can sign up again anytime on our website. For help, our friendly live chat team is available Monday-Friday, 12:00pm to 8pm AEDT.`n`n------------------------------`n`nOrder abandoned",

        "Multiple NTDs", "NBN Order Held`n`n------------------------------`n`nHi xxx,`n`nWe wanted to update you on your recent NBN order. It's currently delayed because NBN have advised that there are multiple HFC NBN boxes at your location.`n`nPlease reply to this email with a photo of the HFC NBN box you are wanting your service established on (including a photo of the MAC and Serial Number details which are located on the sticker).`n`nIf you have any questions, you can reply to this email or just hop on our live chat, and our friendly team will assist you in no time. We're available Monday to Friday, from 12:00pm to 8pm AEDT.`n`n------------------------------`n`nHey Buddy Telco here{!} We are unable to process your order as there is more than one NBN device at your property. Please respond to our email with a photo of the bottom of the NBN device you would like to use, or reach out via LiveChat.",

        "Signal Issue","Hey " CustomerNameSanitised ",`n`nWhile your service may be online, the signal check on your NBN device is failing and the order is unable to complete.`n`n1. Please unscrew the coaxial cable (TV antenna) from the NBN device.`n`n2. In the back of your nbn box there should be a little reset hole, please try holding a paperclip or pin in your nbn box for 15 seconds to reset it.`n`n3. Now screw the coaxial cable back in.`n`nOnce you have done this let us know and we will try and push the order back through.`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nThe signal check on your NBN device is still failing and the order is unable to complete. Please either respond to this email with an appropriate appointment time selected from below, or reach out via LiveChat and we can get you booked in.`n`nIf the service remains in this state it will eventually be disconnected by NBN.`n`nAppointment times:`n`n`n------------------------------`n`nHey, Buddy Telco here{!} We are reaching out as your service has a signal issue and the order is unable to complete. Please respond to our email or come through LiveChat."
        )

    Global FTTCMap := Map(
        "Day 1", "Order Activation`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to update you on your recent NBN order. Currently NBN is unable to detect the FTTC NCD connected. Please ensure that you have a DSL cable connected from the telephone socket on the wall to the wall socket port on the NCD.`n`nIf you have multiple telephone sockets, try each socket for 30 minutes. Typically, the correct socket is the one closest to the front of the house. You`'re looking to see if the chain light goes solid and the DSL light starts flashing on the NCD.`n`nIf you have any questions, you can reach out here or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nThanks for your understanding. We can`'t wait to get you up and running.`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team so we can get things moving. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nSMS and Email Sent",

        "Day 2", "Order Abandonment`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to update you on your recent NBN order. Currently NBN is unable to detect the FTTC NCD connected. Please ensure that you have a DSL cable connected from the telephone socket on the wall to the wall socket port on the NCD.`n`nIf you have multiple telephone sockets, try each socket for 30 minutes. Typically, the correct socket is the one closest to the front of the house. You`'re looking to see if the chain light goes solid and the DSL light starts flashing on the NCD.`n`nIf you have any questions, you can reach out here or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nIf we don`'t hear from you by " newDate ", we`'ll have to abandon your order. We don`'t want you to miss out, so please reach out soon.`n`nThanks for your understanding. We can`'t wait to get you up and running.`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team before " newDate " or we will have to abandon your order. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nSMS and Email Sent " newDate "",

        "Day 3", "Order Abandoned`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing well.`n`nSince we haven`'t heard back from you, we`'ve Abandoned your NBN order. But don`'t worry, it`'s super easy to sign back up on our website.`n`nNeed help signing up? Just hop onto our live chat, and our friendly team will be happy to assist you. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nHave a great day.`n`n------------------------------`n`nHey there. It`'s Buddy Telco. Since we haven`'t heard from you, we`'ve abandoned your NBN order. You can sign up again anytime on our website. For help, our friendly live chat team is available Monday-Friday, 12:00pm to 8pm AEDT`n`n------------------------------`n`nOrder Abandoned",

        "Connect Router", "Hey, Buddy Telco here just reaching out about your order. Please connect your router to your NBN device and your order will be able to complete.`n`n------------------------------`n`nNBN Order Activation`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe are reaching about your NBN order. We can see the NBN connection device is connected and online but there is no router connected.`n`nPlease connect and configure your router as this will allow the order to complete. If you need a hand getting your router conencted please reach out to our LiveChat team between 12pm and 8pm AEDT, or check out our router guides at https://www.buddytelco.com.au/help/{#}router`n`nRegards,`n" csTitle ""
    )

    Global FTTPMap := Map(
        "Multiple UNI-D", "Multiple UNI-D Ports`n`n------------------------------`n`nHi xxx,`n`nWe hope you're doing great.`n`nWe wanted to update you on your recent NBN order. It's currently delayed because NBN have advised that there is already more than one connection on the NTD. `n`nDue to this we need to clarify which port you would like us to use. Please provide us with the port number of the current you would like us to take over.`n`nIf you have any questions, you can reply to this email or just hop on our live chat, and our friendly team will assist you in no time. We're available Monday to Friday, from 12:00pm to 8pm AEDT.`n`n------------------------------`n`nHey Buddy Telco here{!} We are unable to process your order as there is already more than one connection at your address. Please respond to our email to let us know which port you would like us to use, or reach out via LiveChat.",
        
    )

    Global ValidationMap := Map(
        "Day 1", "Order Validation`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to touch base about your recent NBN order, currently your order has failed the mobile validation stage. Unfortunately, we can`'t move forward with it until we hear from you.`n`nTo move your order forward, simply contact our live chat team to complete the two-factor verification and we`'ll take care of the rest. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nThanks for your understanding. We can`'t wait to get you up and running.`n`nRegards`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team so we can get things moving. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks`n`n------------------------------`n`nSent SMS and Email",

        "Day 2", "Order Activation`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to touch base about your recent NBN order, currently your order has failed the mobile validation stage. Unfortunately, we can`'t move forward with it until we hear from you.`n`nTo move your order forward, simply contact our live chat team to complete the two-factor verification and we`'ll take care of the rest. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nIf we don`'t hear from you by " newDate ", we`'ll have to cancel your order. We don`'t want you to miss out, so please reach out soon.`n`nThanks a bunch for your understanding. We can`'t wait to get you up and running.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. As we haven`'t heard from you, we will abandon your order on " newDate ". You can sign up again anytime on our website. For help, our friendly live chat team is available Monday-Friday, 12:00pm to 8pm AEDT`n`n------------------------------`n`nSet abandonment date for " newDate "",

        "Day 3", "Order Abandonment`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing well.`n`nSince we haven`'t heard back from you, we`'ve abandoned your NBN order. But don`'t worry, it`'s super easy to sign back up on our website.`n`nNeed help signing up? Just hop onto our live chat, and our friendly team will be happy to assist you. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nHave a great day.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. Since we haven`'t heard from you, we`'ve abandoned your NBN order. You can sign up again anytime on our website. For help, our friendly live chat team is available Monday-Friday, 12:00pm to 8pm AEDT.`n`n------------------------------`n`nOrder abandoned"
    )

    Global BanlistingMap := Map(
        "Day 1", "Order Failure`n`n------------------------------`n`nHey ,`n`nWe hope you`'re doing great.`n`nWe wanted to touch base about your recent NBN order, seems like some details are flagging as ban listed. Unfortunately, we can`'t move forward with it until we hear from you.`n`nBut don`'t worry, it`'s super easy to get in touch. Just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nIf we don`'t hear from you by [insert date], we`'ll have to cancel your order. We don`'t want you to miss out, so please reach out soon.`n`nThanks a bunch for your understanding. We can`'t wait to get you up and running.`n`nRegards`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team so we can get things moving. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks`n`n------------------------------`n`nSent SMS and Email for banlisting",
    )

    Global FailedPaymentMap := Map(
        "Day 1", "Hey there. It's Buddy Telco. We need to chat about your hardware order. Please reach out to our live chat team so we can get things moving. We're here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nDear " CustomerNameSanitised ",`n`nI hope this email finds you well{!}`n`nJust reaching out to let you know that the $35 payment for the first installment and shipping cost of your hardware unfortunately didn't go through. Could you please let us know when you'd like us to reattempt the payment?`n`nIf there's anything we can do to assist, feel free to reach out as we're always happy to help{!}`n`nRegards,`n" csTitle "",

        "Day 2", "Hey there. It's Buddy Telco. We need to chat about your hardware order. Please reach out to our live chat team so we can get things moving. We're here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you're doing great.`n`nWe wanted to update you on your recent NBN order. It's currently delayed because your hardware debit has failed.`n`nIf you have any questions, you can reach out here or just hop on our live chat, and our friendly team will assist you in no time. We're available Monday to Friday, from 12:00pm to 8pm AEDT.If we don't hear from you by " newDate ", we'll have to abandon your order. We don't want you to miss out, so please reach out soon.`n`nThanks for your understanding. We can't wait to get you up and running.`n`nRegards,`n" csTitle ""
    )

    Global PaymentMap := Map(
        "Day 1", "Missing Payment Details`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to touch base about your recent NBN order, currently your account is missing payment details. Unfortunately, we can`'t move forward with the order until we get payment details added to your account.`n`nBut don`'t worry. You can update these details via the Buddy app or web portal, or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nThanks a bunch for your understanding. We can`'t wait to get you up and running.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team so we can get things moving. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks.`n`n------------------------------`n`nSent SMS and Email",

        "Day 2", "Missing Payment Details`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing great.`n`nWe wanted to touch base about your recent NBN order, currently your account is missing payment details. Unfortunately, we can`'t move forward with the order until we get payment details added to your account.`n`nBut don`'t worry, you can update these details via the Buddy app or web portal, or just hop on our live chat, and our friendly team will assist you in no time. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nIf we don`'t hear from you by " newDate ", we`'ll have to cancel your order. We don`'t want you to miss out, so please reach out soon.`n`nThanks a bunch for your understanding. We can`'t wait to get you up and running.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. We need to chat about your NBN order. Please reach out to our live chat team before " newDate " or we will have to abandon your order. We`'re here Monday to Friday, from 12:00pm to 8pm AEDT. Thanks`n`n------------------------------`n`nSent SMS and Email " newDate "",

        "Day 3", "Order abandonment`n`n------------------------------`n`nHey " CustomerNameSanitised ",`n`nWe hope you`'re doing well.`n`nSince we haven`'t heard back from you, we`'ve abandoned your NBN order. But don`'t worry, it`'s super easy to sign back up on our website.`n`nNeed help signing up? Just hop onto our live chat, and our friendly team will be happy to assist you. We`'re available Monday to Friday, from 12:00pm to 8pm AEDT.`n`nHave a great day.`n`nRegards,`n" csTitle "`n`n------------------------------`n`nHey there. It`'s Buddy Telco. Since we haven`'t heard from you, we`'ve abandoned your NBN order. You can sign up again anytime on our website. For help, our friendly live chat team is available Monday-Friday, 12:00pm to 8pm AEDT.`n`n------------------------------`n`nOrder abandoned",
    )

    Global NBNCompMap := Map(
        "Templates", "Dear " CustomerNameSanitised ",`n`nComplaints may be made to the NBN and updates on the progress of complaints can be obtained by contacting the NBN Complaints Team on the following: `n`nThe NBN Co website online form at `'Contact Us`'. `nwww.nbnco.com.au/online_channel/contact_us`nby email to complaints@nbnco.com.au`nby phone to 1800 687 626`nby mail Locked Bag 27, Gold Coast MC, 9726`nby fax to Complaint Team 1800 106 033.`n`n------------------------------`n`nDear " CustomerNameSanitised ",`n`nAs discussed earlier today in relation to your nbn connection. Please be advised we have raised a NBN formal complaint on your behalf. An NBN Case Manager will contact yourself within the next 5 business days, if you haven`'t been contacted within this time please do not hesitate to let us know.`n`nComplaint reference details are as follows:`nNBN Formal Complaint Reference Number: XXXX`nNBN Complaints Team Contact: 1800 687 626`n`nPlease do not hesitate to contact our Customer Service team directly on 1300 028 339 should you have any further questions.",
        )

    Global RaisingMap := Map(
        "Templates", "Complaints - Template`n`nIssue: [Describe the issue or problem the customer is facing, providing any relevant background information, incidents, or observations that led to their concerns.]`n`nWhat Has Been Done So Far: [Outline any actions you have taken to address the issue thus far, such as troubleshooting, external escalation, explanation of our policies and procedures, or bringing it to the attention of your supervisor. Have we done everything we can internally to resolve the customer`'s concerns, including following correct escalation pathways, if not, why not?]`n`nCustomer`'s Desired Outcome from the Complaint: [Clearly state what resolution or action that the customer has advised would effectively address the issue.]"
        )

    Global ClarificationMap := Map(
        "Templates", "Dear " CustomerNameSanitised ",`n`nThanks for letting us know about this issue.`n`nAs you have not contacted our customer service team on this matter yet, I have interpreted this as a request for technical support and have raised a fault with our customer service team to help you resolve this issue in the Buddy Telco. If you have issues with the way our customer service team handles the fault or with how long they take to progress it, please feel free to reach back out to the complaints team and we will take a look into this for you.`n`nIf you did wish to lodge a formal complaint please respond to this email to advise us and a complaints officer will reach out to you soon.`n`n------------------------------`n`nDear " CustomerNameSanitised ",`n`nThank you for taking the time to get in touch with us regarding this matter. `n`nUnfortunately I have been unable to identify you on any account at Buddy Telco. `nIf you are contacting us regarding an account that you are not authorised on please have the account holder reach out to us through one of the following methods:`n`nPhoning 1300 028 339 - Monday to Friday 12pm to 8pm AEDT`nEmailing complaints@buddytelco.com.au`nCompleting the online complaint form at the bottom of this page`nPost at PO Box 3351, Gippsland Mail Centre VIC 3841`n`nOnce we are able to validate your complaint against a Buddy Telco  we will be more than happy to investigate your issue."
        )

    Global ResolutionsMap := Map(
        "Templates", "Dear " CustomerNameSanitised ",`n`nThank you for the response.`n`nI have applied this credit and marked this complaint as resolved. You should receive an email confirming this credit within 24 hours.`nIf you have any further questions or concerns, please do not hesitate to contact our customer service team via LiveChat.`n`n------------------------------`n`nDear " CustomerNameSanitised ",`n`nThank you for the response.`n`nI have submitted this refund to our finance team and marked this complaint as resolved. You should receive this refund within 10 business days. Please feel free to reach out to us for updates on this.`n`nIf you have any further questions or concerns, please do not hesitate to contact our customer service team via LiveChat.`n`n------------------------------`n`nDear " CustomerNameSanitised ",`n`nThank you for the response.`n`nI have applied this discount and marked this complaint as resolved. You should see this reflected on future invoices.`nIf you have any further questions or concerns, please do not hesitate to contact our customer service team via LiveChat",
        )

    Global ChangesMap := Map(
        "Changing PRD", "Dear " CustomerNameSanitised ",`n`nPlease be advised that I am moving the proposed resolution date of your complaint to XXX. This is occurring due to xxx. `n`nIf at any point you are unsatisfied with our handling of your complaint, its progress or outcome, you may opt to seek external dispute resolution via an external dispute resolution provider such as the Telecommunications Industry Ombudsman.`n`nThe Telecommunications Industry Ombudsman can be contacted by:`nPhone: 1800 062 058`nFax: 1800 630 614`nOnline: http://www.tio.com.au/making-a-complaint",
        )

    Global TIOMap := Map(
        "Templates", "Dear " CustomerNameSanitised ",`n`nIf you are unsatisfied with our response to your complaint and you wish to seek external dispute resolution, you may do so via the Telecommunications Industry Ombudsman.`nThe Telecommunications Industry Ombudsman can be contacted by:`n`nPhone: 1800 062 058`nFax: 1800 630 614`nOnline: http://www.tio.com.au/making-a-complaint`n`n------------------------------`n`nDear " CustomerNameSanitised ",`n`nI invite you to respond to this email within 10 working days. If we do not receive a response within 10 working days, the matter will be considered resolved and your complaint will be closed.`n`nIf your Ombudsman case progresses further we will receive notification from the Ombudsman and your complaint will be reopened and addressed accordingly.",
        )
    Global ContactsMap := Map(
        "SMS", "Hey " CustomerNameSanitised ", it's the Buddy Telco Complaints Team. Just reaching out to see if you had a chance to read the email that was sent to you in regards to your active complaint. Please get back to us when you are able to.",

        "Email", "Buddy Telco - Complaint #XXX`n`n------------------------------`n`nHey " CustomerNameSanitised ", `n`nIt is " csTitle " from the Buddy Telco complaints team. `n`nI just wanted to reach out as we have not heard back from you regarding your complaint. `n`nPlease reach out when you have a chance as we would like to work together with you to reach a resolution. If the previously mentioned offer is acceptable, please let us know and we will take action.",

        "5 Attempts", "Dear " CustomerNameSanitised ",`n`nThank you for reaching out in regards to [Complaint Number]. We understand the importance of resolving this matter and have made several attempts to contact you to discuss it. We have made several attempts to contact you on these dates:`n`n[xx/xx/xx]: [Method]`n[xx/xx/xx]: [Method]`n[xx/xx/xx]: [Method]`n[xx/xx/xx]: [Method]`n[xx/xx/xx]: [Method]`n`nAs we have not received a response from you despite our repeated attempts, we kindly request that you contact us within 10 business days to continue the resolution process. If we do not hear from you by this time, we will consider your complaint resolved and will mark it as closed in our records.`n`nIf you wish to continue with this complaint or if there are any other issues you'd like to discuss, please reach out to us as soon as possible.`n`nThank you for your attention to this matter. We look forward to your response.`n`nRegards,`n" csTitle ""
        )

    Global TCSGeneralMap := Map(
        "Availability", "5.1 Service availability`n`n(a) Subject to your rights under the Consumer Law, we aim to provide, but cannot guarantee, a continuous Service free of any Interruptions.`n`n(b) You are aware that we may rely on Suppliers for supplying a Service to you. This means that circumstances beyond our control may cause interruptions to the Service from time to time.",
        
        "Maintenance", "5.2 Maintenance and fault restoration`n`n(a) Subject to your rights under the Consumer Law and to the extent permitted by law, we’re not obliged to restore Service faults caused by:`n`n- Force Majeure Events, or`n- Planned outages",

        "Support", "5.3 Technical support and training`n`nVirtual tech support`n`n(a) We offer some technical support, as set out on our website at buddytelco.com.au/help. However, we’re not responsible for training to use your Service.`n`n(b) We’re not responsible for, and may not be able to provide support for, any fault caused by:`n`n- Customer Equipment,`n- the Service interacting with third party software you use,`n- issues with wireless connectivity from a wireless access point or router to your computer, or`n- Services provided by any third party supplier or carrier (other than our Suppliers)",

        "EU Obligations", "6.2 Your obligations`n`nAssistance and access`n`n(f) You agree to give all reasonable assistance, information, access, that we reasonably require to enable us to perform our obligations under this Agreement and deliver Services to you.",

        "Data", "6.3 Obligations to retain data`n`nYou agree that we (or a Supplier) may take reasonably necessary steps to comply with the Law in relation to the Services we provide you. This may include:`n`n(a) intercepting communications made using a Service, and`n(b) monitoring and retaining data relating to your Service or accessed or transmitted by you while using the Service, and`n(c) providing such data to persons authorised by law.`n`n------------------------------`n`n11.2 Consent to collection and use`n`n(a) You agree we may collect, use, and disclose your Personal Information in line with our Privacy Policy, which we update from time to time.`n`n------------------------------`n`n11.3 Use of Personal Information`n`n(a) In particular, you acknowledge and agree that we will use your Personal Information:`n`n- to issue Bills and collect Fees and other amounts you owe under this Agreement, and This means that we collect and use information regarding your credit card details or direct debit bank account details because you must pay for the Services by either direct debit or standing credit card authorisation`n`n------------------------------`n`n11.8 Access to information`n`nWhere we hold any Personal Information about you, you may request access to that information. We will provide you with access to most Personal Information that we have about you (once we have verified your request is in good faith). In some cases that will not be possible, in which case, we will tell you why.",

        "Access", "9.3 We may need access to maintain and install Service Equipment`n`n(a) We (or our Supplier) may need access to your premises from time to time in connection with:`n`n- the provision and maintenance of the Service Equipment or a Service, and`n- the installation of any Facility, Equipment or cabling on your premises required for a Service.`n`nThis right of access continues until Service Equipment is returned to us, even if the Services are cancelled.`n`n(b) You agree to allow us reasonable access to the Service Equipment during business hours (or such other times agreed with you) and on reasonable notice.`n`n- If you do not allow this access, we may need to restrict, suspend, or cancel your Service."
        )

    Global TCSBillingMap := Map(
        "Fees", "13.1 Fees`n`nYou’re responsible for your Service`n`n(a) You’re responsible for paying all Fees that arise from using the Service, whether it is your use or anyone else with or without your consent.`n`n(b) If your Service is used to access the Facilities or Services of another service provider, then amounts charged by that other service provider are your responsibility (unless our Agreement with you specifies otherwise).`n`n- You’ll need to pay us those charges and if we are charged, we’ll Bill you for them",

        "Payment Methods", "14.3 Methods of payment`n`n(a) When you pay for your Services, you’ll need to pay by direct debit from either a credit card standing authorisation or bank account.`n`n(b) If we incur fees from your bank or have to pay fees to your bank, we reserve the right to recover these amounts from you.`n`n(c) If your preferred payment method is declined, we reserve the right to attempt to take the required payment for up to 10 business days after the initial due date.",

        "Disputes", "15.4 Disputed Bills`n`n(a) If you genuinely dispute a Bill or claim a refund for overpayment of any Fees under our Agreement you should do so within 5 months of the date of the Bill to which the disputed amount or alleged overpayment relates.",

        "Debit Dishonours", "15. Other fees you may need to pay`n`nDishonoured direct debit transaction or credit card authorisation`n`n(a) If we agree a direct debit arrangement with you for your Service Fees and:`n● your payment is declined by your payment provider, and`n● your payment provider charges us a fee as a result,`nthen we may recover from you costs we incur as a result of a declined or dishonoured transaction.",

        "Further Actions", "Debt recovery`n`n(b) If we, acting reasonably, use debt recovery services to recover outstanding amounts from you, then we may recover those collection costs, such as legal costs.`n`n------------------------------`n`nConnection Fee`n`n(d) We may charge you a Fee to re-connect your Service. This Fee won’t apply if disconnection was caused by:`n● our error or failure to perform our obligations under the Agreement or `n● the result of any of the events specified in clause 24.3 (External factors cause us to restrict, suspend or cancel).",

        "Other Fees", "15. Other fees you may need to pay`n`nDishonoured direct debit transaction or credit card authorisation`n`n(a) If we agree a direct debit arrangement with you for your Service Fees and:`n- your payment is declined by your payment provider, and`n- your payment provider charges us a fee as a result, then we may recover from you costs we incur as a result of a declined or dishonoured transaction."
    )

    Global TCSSuspensionMap := Map(
        "Service Use", "24.2 Your actions cause us to restrict, suspend or cancel`n`nWe may need to restrict, suspend or cancel a Service in the following circumstances:`n`nService use issues`n`n(a) If you leave the premises where we supply a Service to you without our prior agreement.`n(b) If we can’t enter premises to inspect, repair, or maintain Equipment or cabling connected with a Service.`n(c) If you fail to comply with an Fair Use Policy after we give you reasonable notice to comply.`n(d) If you fail to fix a defect or shortcoming in Customer Equipment or your cabling within 30 days of a request from us.`n(e) If you do (or allow) anything which in our reasonable opinion may jeopardise the standard, intended operation of a Service.`n(f) If your use of a Service interferes with our network or a Supplier’s network and you fail to rectify the situation within 24 hours from our request.`n(g) If you become a Carrier or Carriage Service Provider within the meaning of the Telco Act.",
        
        "Poor Behaviour", "Immediate cancellation for poor behaviour`n`n(h) If we reasonably believe you’ve engaged in fraud or illegal conduct in your Application.`n(i) If you abuse or harass our staff or our contractors in the conduct of their duties.`n(j) If you threaten to harm, attempt to harm or cause actual harm to Buddy Telco staff, our contractors or property.",

        "Payment Issues", "Payment issues`n`n(k) If you experience an Insolvency Event and we reasonably believe we are unlikely to receive payments from you for Services when they become payable.`n(l) If you fail to pay fees on time and we’re entitled to restrict, suspend, or cancel the Service under clause 14.5 (Late payments and actions we may take).`n(m) If you do not provide prepayment for Services when we request under clause 15.3 (Prepayment)`n(n) If we reasonably believe you are a credit risk.`n`nThe following are examples of reasonable grounds for believing you may be a credit risk:`n- Your Service use is unusually high compared to previous use and you fail to respond to notices from us about that use.`n- You have a payment history indicating late payments, dishonoured payments or failures to pay, or you fail to pay or replenish a security deposit.`n- We become aware you may be experiencing an Insolvency Event and we have taken reasonable steps to notify you of the restriction, suspension, or cancellation of the Service.`n`n(o) You are in material breach of any of the terms of our Agreement with you."
    )

    Global TCSChangesMap := Map(
        "TOS Changes", "18.1 We may need to change the terms of our Agreement with you`n`nChanges due to business decisions`n`n(c) We may also need to change the terms of our Agreement with you for our own legitimate business purposes, including:`n- changes we make to keep pace with technology updates,`n- changes in our supply chain requirements,`n- changes in the technical Services we have available to support a Service or feature,`n- changes in our business strategy, and many other business reasons for changing Services and features."
    )
}
